### ISSUE TITLE
mac版无法运行

### ISSUE THREAD

**Issue by 4lan5** [zigslice/exceltk#10]
文件信息：
$ md5sum exceltk.0.1.3.pkg
646d6a6da18e978bb82c211c5265cf46  exceltk.0.1.3.pkg

安装正常，在执行时报错：
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Exceltk.MarkDownExtension.<ToMd>d__1.MoveNext() in /Users/feilong/Desktop/dev/exceltk/src/Exceltk/Extension/MarkDownExtension.cs:line 45
   at Exceltk.Program.Xls2MarkDown(CommandParser cmd) in /Users/feilong/Desktop/dev/exceltk/src/Exceltk/Program.cs:line 126
   at Exceltk.Program.Main(String[] args) in /Users/feilong/Desktop/dev/exceltk/src/Exceltk/Program.cs:line 15
Abort trap: 6

**Comment by fanfeilong** [comment]
Can you send me the excel file?

fanfeilong@gmail.com

**Comment by 4lan5** [comment]
已发，请查收

**Comment by zllpCodes** [comment]
I met this question too. How did you fix it?
